name: Jade
favicon: null
layout_spectrum: 0.8160704269539565
typography_spectrum: 0.8171092043630779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2448373429942876
  lightness: 0.9565530840773135
  saturation: 0.9779326058924198
  rhythmicContrast: 0.8085854526143521
purpose: []
